branch-defaults:
  develop:
    environment: Bibinoserver-env-2
environment-defaults:
  Bibinoserver-env:
    branch: null
    repository: null
  Bibinoserver-env-2:
    branch: null
    repository: null
global:
  application_name: bibino-server
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
