module.exports = {
  awsAccessKeyID: process.env.AWS_ACCESS_KEY_ID,
  awsSecretAccessKy: process.env.AWS_SECRET_ACCESS_KEY,
  databaseURI: process.env.DATABASE_URI,
  databasePassword: process.env.DATABASE_PASSWORD,
  firebaseDatabaseURL: process.env.FIREBASE_DATABASE_URL,
  appPrivateKey: process.env.PRIVATE_KEY,
  googleVisionApiUrl: process.env.GOOGLE_VISION_API_URL,
  firebaseType: process.env.FIREBASE_TYPE,
  fireebaseProjectId: process.env.FIREBASE_PROJECT_ID,
  firebasePrivateKeyId: process.env.FIREBASE_PRIVATE_KEY_ID,
  firebasePrivateKey: process.env.FIREBASE_PRIVATE_KEY,
  firebaseClientEmail: process.env.FIREBASE_CLIENT_EMAIL,
  firebaseClientId: process.env.FIREBASE_CLIENT_ID,
  firebaseAuthUrl: process.env.FIREBASE_AUTH_URL,
  firebaseTokenUrl: process.env.FIREBASE_TOKEN_URL,
  firebaseAuthProviderX509CertUrl:
    process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
  firebaseClientX509CertUrl: process.env.FIREBASE_CLIENT_X509_CERT_URL,
};
